### ISSUE TITLE
Create interfaces

### ISSUE THREAD

**Issue by levkovalenko** [apmath-web/clients#2]
write:
- model interface
- viewmodel interface
- message interface
- validation interface
- repository interface

dependencies: #1

**Comment by levkovalenko** [comment]
I'll finish this task at 12.03.2019

**Comment by malinink** [comment]
When there will be more than one developer in project, I would suggest to use milestones then.

**Comment by levkovalenko** [comment]
@malinink it's good idea, it will be easier to control tasks
